### ISSUE TITLE
Questions about GPU resources

### ISSUE THREAD

**Issue by yaoshentao** [salesforce/BiST#1]
Hello,
Thank you for your open source code and your interesting work！There were some problems in the process of using it.
When I execute code on the Action task in your branch tgif-qa, I get a cuda out of memory error. I have modified the batchsize from 32 to 16, but the same situation still occurs. For batchsize=16, this error occurred when epoch=40. I would like to know what the size of the GPU memory you are using is and the error I get are normal? My GPU memory is 12GB.I lost my error information. If you need this error information, I can run it again and give you a screenshot.

**Comment by henryhungle** [comment]
Hi @yaoshentao I can run the code on the Action task (batch size=16) on a single GPU, Tesla V100-SXM2-16GB. With batch size 32, I also had Cuda out of memory error. 

Based on my experience, on Action and Transition tasks, you probably should use a small batch size to avoid memory issues (smaller than the batch size on FrameQA and Count tasks).

**Comment by yaoshentao** [comment]
Hi, Thanks for your suggestion!
