### ISSUE TITLE
./scripts/path.sh: No such file or directory

### ISSUE THREAD

**Issue by 401460453** [salesforce/BiST#4]
I noticed that both exec.sh and test.sh require ./scripts/path.sh,but i can't find it,should I write by myself?Or just to ignore it,looking forward to your reply.

**Comment by henryhungle** [comment]
Sorry for the late response.

The `./scripts/path.sh` is actually a legacy code from the MTN evaluation script. You can ignore or remove this line. 

You will notice that the `path.sh` is already included in the `dstc7avsd_eval` folder and will be executed when calling the `./dstc7avsd_eval.sh`: 

https://github.com/salesforce/BiST/blob/73913dc99f21ea61ae34dffbe96cc4cb4e810ad9/scripts/exec.sh#L173

https://github.com/salesforce/BiST/blob/73913dc99f21ea61ae34dffbe96cc4cb4e810ad9/scripts/test.sh#L113
